### ISSUE TITLE
Size of the downloaded DEM

### ISSUE THREAD

**Issue by SaiedFarag** [nst-guide/terrain#7]
Since we have to download DEM to generate slope, what if we need to generate a slope degrees layer of the entire U.S. with a 1-mater resolution?
the size of the needed DEM is very very huge. how do we download and store it to start working on it using GDAL?
I think the size of this DEM will be +700 TB !!!!

**Comment by kylebarron** [comment]
this code isn't ideal for something of the entire us. you can use it on the cloud if you wish, but you need to do more iterative processing to work with such large data.

**Comment by SaiedFarag** [comment]
Thanks,
I would appreciate any advice to implement a slope layer a a global scale or U.S. coverage like Caltopo.
